# Generated by Django 3.2.16 on 2022-10-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='user_name',
        ),
        migrations.AddField(
            model_name='recipes',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Your name'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='body',
            field=models.TextField(verbose_name='Ingredients and Method'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='djangouploads/files/covers', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe_name',
            field=models.CharField(max_length=100, verbose_name='Recipe Title'),
        ),
    ]
