# Generated by Django 3.2.16 on 2022-10-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
    ]
