# Generated by Django 3.2.16 on 2022-12-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
